// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBYFvJjV2WLkTrerAFET8v1LxN9eWYDqUE',
    appId: '1:72354754478:web:f128e00ad15393a75e223f',
    messagingSenderId: '72354754478',
    projectId: 'hhozha',
    authDomain: 'hhozha.firebaseapp.com',
    storageBucket: 'hhozha.firebasestorage.app',
    measurementId: 'G-0PS6K42T24',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8DylurENtbLPcbyyWAv0tTZBr6DWqyqk',
    appId: '1:72354754478:android:d54a4e99bb30eed35e223f',
    messagingSenderId: '72354754478',
    projectId: 'hhozha',
    storageBucket: 'hhozha.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVbn0oKi_aTEEPmq-2_MpxPM1WBy3Mluw',
    appId: '1:72354754478:ios:56b21203fdc090445e223f',
    messagingSenderId: '72354754478',
    projectId: 'hhozha',
    storageBucket: 'hhozha.firebasestorage.app',
    iosBundleId: 'com.example.hhozha',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVbn0oKi_aTEEPmq-2_MpxPM1WBy3Mluw',
    appId: '1:72354754478:ios:56b21203fdc090445e223f',
    messagingSenderId: '72354754478',
    projectId: 'hhozha',
    storageBucket: 'hhozha.firebasestorage.app',
    iosBundleId: 'com.example.hhozha',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBYFvJjV2WLkTrerAFET8v1LxN9eWYDqUE',
    appId: '1:72354754478:web:c2a519f3d87e29c45e223f',
    messagingSenderId: '72354754478',
    projectId: 'hhozha',
    authDomain: 'hhozha.firebaseapp.com',
    storageBucket: 'hhozha.firebasestorage.app',
    measurementId: 'G-Z5M2NJLPHL',
  );
}
